name: Commit CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: Checkout Main branch
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: CI
        path: CI

    - name: Build Commit branch
      run: |
        cd $GITHUB_WORKSPACE
        make

    - name: Build CI branch
      run: |
        cd CI
        make

    - name: Compare Test "ra,row,ba,col,bg"
      run: |
        cd $GITHUB_WORKSPACE
        ./bin2ddr -i ready-to-run/int-gcpt.bin -o commit.bin -m "ra,row,ba,col,bg"
        cd CI
        ./bin2ddr -i ready-to-run/int-gcpt.bin -o CI.bin -m "ra,row,ba,col,bg"

        PR_MD5=$(md5sum $GITHUB_WORKSPACE/commit.bin | awk '{print $1}')
        CI_MD5=$(md5sum CI.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch"
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i ready-to-run/int-gcpt.bin -o commit.bin -m "ra,row,ba,col,bg,ch"
        cd CI
        ./bin2ddr -i ready-to-run/int-gcpt.bin -o CI.bin -m "ra,row,ba,col,bg,ch"

        PR_MD5=$(md5sum $GITHUB_WORKSPACE/commit_1.bin | awk '{print $1}')
        CI_MD5=$(md5sum CI_1.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch" -s
      run: |
          cd $GITHUB_WORKSPACE
          ./bin2ddr -i ready-to-run/int-gcpt.bin -o commit.bin -m "ra,row,ba,col,bg,ch" -s
          cd CI
          ./bin2ddr -i ready-to-run/int-gcpt.bin -o CI.bin -m "ra,row,ba,col,bg,ch" -s

          PR_MD5=$(md5sum $GITHUB_WORKSPACE/commit_3.bin | awk '{print $1}')
          CI_MD5=$(md5sum CI_3.bin | awk '{print $1}')
          if [ "$PR_MD5" != "$CI_MD5" ]; then
            echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
            echo "Output differs from CI"
            exit 1
          fi
