name: Compare PR with Main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Checkout Main branch
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        path: main

    - name: Build PR branch
      run: |
        cd $GITHUB_WORKSPACE
        make

    - name: Build Main branch
      run: |
        cd main
        make

    - name: Compare Test "ra,row,ba,col,bg"
      run: |
        cd $GITHUB_WORKSPACE
        ./bin2ddr -i ready-to-run/int-gcpt.bin -o pr.bin -m "ra,row,ba,col,bg"
        cd main
        ./bin2ddr -i ready-to-run/int-gcpt.bin -o main.bin -m "ra,row,ba,col,bg"

        PR_MD5=$(md5sum $GITHUB_WORKSPACE/pr.bin | awk '{print $1}')
        MAIN_MD5=$(md5sum main.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$MAIN_MD5" ]; then
          echo "PR MD5: $PR_MD5"
          echo "Master MD5: $MAIN_MD5"
          echo "Output differs from main"
          exit 1
        else
          echo "Output is the same as main"
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch"
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i ready-to-run/int-gcpt.bin -o pr.bin -m "ra,row,ba,col,bg,ch"
        cd main
        ./bin2ddr -i ready-to-run/int-gcpt.bin -o main.bin -m "ra,row,ba,col,bg,ch"

        PR_MD5=$(md5sum $GITHUB_WORKSPACE/pr_1.bin | awk '{print $1}')
        MAIN_MD5=$(md5sum main_1.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$MAIN_MD5" ]; then
          echo "PR MD5: $PR_MD5"
          echo "Master MD5: $MAIN_MD5"
          echo "Output differs from main"
          exit 1
        else
          echo "Output is the same as main"
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch" -s
      run: |
          cd $GITHUB_WORKSPACE
          ./bin2ddr -i ready-to-run/int-gcpt.bin -o pr.bin -m "ra,row,ba,col,bg,ch" -s
          cd main
          ./bin2ddr -i ready-to-run/int-gcpt.bin -o main.bin -m "ra,row,ba,col,bg,ch" -s

          PR_MD5=$(md5sum $GITHUB_WORKSPACE/pr_3.bin | awk '{print $1}')
          MAIN_MD5=$(md5sum main_3.bin | awk '{print $1}')
          if [ "$PR_MD5" != "$MAIN_MD5" ]; then
            echo "PR MD5: $PR_MD5"
            echo "Master MD5: $MAIN_MD5"
            echo "Output differs from main"
            exit 1
          else
            echo "Output is the same as main"
          fi