name: Commit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  bin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}

    - name: Checkout Main branch for push event
      if: github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: CI
        path: CI

    - name: Checkout Main branch for pull request
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: main
        path: CI

    - name: Build Commit branch
      run: |
        cd $GITHUB_WORKSPACE
        make

    - name: Build CI branch
      run: |
        cd CI
        make
     
    - name: Compare Test "ra,row,ba,col,bg"
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/int-gcpt.bin -o r1_commit.bin -m "ra,row,ba,col,bg"
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/int-gcpt.bin -o r1_CI.bin -m "ra,row,ba,col,bg"

        PR_MD5=$(md5sum r1_commit.bin | awk '{print $1}')
        CI_MD5=$(md5sum r1_CI.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch"
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/int-gcpt.bin -o rc2_commit.bin -m "ra,row,ba,col,bg,ch"
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/int-gcpt.bin -o rc2_CI.bin -m "ra,row,ba,col,bg,ch"

        PR_MD5=$(md5sum rc2_commit_1.bin | awk '{print $1}')
        CI_MD5=$(md5sum rc2_CI_1.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch" -s
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/int-gcpt.bin -o rc4_commit.bin -m "ra,row,ba,col,bg,ch" -s
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/int-gcpt.bin -o rc4_CI.bin -m "ra,row,ba,col,bg,ch" -s

        PR_MD5=$(md5sum rc4_commit_3.bin | awk '{print $1}')
        CI_MD5=$(md5sum rc4_CI_3.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

  checkpoint-rm-zero:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}

    - name: Checkout Main branch for push event
      if: github.event_name == 'push'
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: CI
        path: CI

    - name: Checkout Main branch for pull request
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: main
        path: CI

    - name: Build Commit branch
      run: |
        cd $GITHUB_WORKSPACE
        make RM_ZERO=1

    - name: Build CI branch
      run: |
        cd CI
        make RM_ZERO=1

    - name: Compare Test "ra,row,ba,col,bg" of Gz
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.gz -o r1_gz_commit.bin -m "ra,row,ba,col,bg"
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.gz -o r1_gz_CI.bin -m "ra,row,ba,col,bg"

        PR_MD5=$(md5sum r1_gz_commit.bin | awk '{print $1}')
        CI_MD5=$(md5sum r1_gz_CI.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch" -s
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.gz -o rc4_gz_commit.bin -m "ra,row,ba,col,bg,ch" -s
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.gz -o rc4_gz_CI.bin -m "ra,row,ba,col,bg,ch" -s

        PR_MD5=$(md5sum rc4_gz_commit_3.bin | awk '{print $1}')
        CI_MD5=$(md5sum rc4_gz_CI_3.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg" of Zstd
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.zstd -o rc1_zstd_commit.bin -m "ra,row,ba,col,bg"
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.zstd -o rc1_zstd_CI.bin -m "ra,row,ba,col,bg"

        PR_MD5=$(md5sum rc1_zstd_commit.bin | awk '{print $1}')
        CI_MD5=$(md5sum rc1_zstd_CI.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi

    - name: Compare Test "ra,row,ba,col,bg,ch" -s
      run: |
        $GITHUB_WORKSPACE/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.zstd -o rc4_zstd_commit.bin -m "ra,row,ba,col,bg,ch" -s
        CI/bin2ddr -i $GITHUB_WORKSPACE/ready-to-run/hmmer_nph3.zstd -o rc4_zstd_CI.bin -m "ra,row,ba,col,bg,ch" -s

        PR_MD5=$(md5sum rc4_zstd_commit_3.bin | awk '{print $1}')
        CI_MD5=$(md5sum rc4_zstd_CI_3.bin | awk '{print $1}')
        if [ "$PR_MD5" != "$CI_MD5" ]; then
          echo "PR MD5: $PR_MD5 , Master MD5: $CI_MD5"
          echo "Output differs from CI"
          exit 1
        fi